# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8jeNtzpzkHP0VwwwZlld4n_A1Pvpf0x
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd

data = pd.read_csv(io.BytesIO(uploaded['Reviews.csv']))
print(data)

data

# checking the null values
data.isnull().sum()

#checking the duplicate data
data.duplicated()

#exploratary data analysis matplotlib and seborn
import seaborn as sns
import matplotlib.pyplot as plt

from wordcloud import WordCloud

combined_text = " ".join(data['Review']) #combine all review text into one string
combined_text

wordcloud = WordCloud(width=800, height = 400, background_color = 'white').generate(combined_text)

plt.figure(figsize=(15,6))
plt.imshow(wordcloud,interpolation='bilinear')
plt.axis('off')
plt.title('word cloud of Reviews')
plt.show()

from collections import Counter

targeted_words = ['good','great','amazing','bad','nor bad']
all_words=" ".join(data['Review']).lower().split() #flatten reviews into a single list of words
word_counts = Counter(all_words)
target_word_count={word: word_counts[word] for word in targeted_words}

plt.figure(figsize=(8,6))
plt.bar(target_word_count.keys(), target_word_count.values(), color=['blue','green','orange','red','black'])
plt.xlabel('words')
plt.ylabel('frequency')
plt.title('Frequency of specific words in reviews')
plt.show()

